# Generated by Django 5.2.17 on 2026-09-14 02:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='preço')),
                ('disponivel', models.BooleanField(default=True, verbose_name='disponível')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='número')),
                ('capacidade', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='preço')),
                ('disponivel', models.BooleanField(default=True, verbose_name='disponível')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aberta_em', models.DateTimeField(auto_now_add=True)),
                ('fechada_em', models.DateTimeField(blank=True, null=True)),
                ('total_fechado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comandas', to='cardapio.mesa')),
            ],
            options={
                'ordering': ['-aberta_em'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantidade', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('observacao', models.CharField(blank=True, max_length=200, verbose_name='observação')),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='cardapio.comanda')),
                ('combo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cardapio.combo')),
                ('prato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cardapio.prato')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='combo',
            name='pratos',
            field=models.ManyToManyField(related_name='combos', to='cardapio.prato'),
        ),
        migrations.AddConstraint(
            model_name='comanda',
            constraint=models.UniqueConstraint(condition=models.Q(('fechada_em__isnull', True)), fields=('mesa',), name='uma_comanda_aberta_por_mesa'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('combo__isnull', True), ('prato__isnull', False)), models.Q(('combo__isnull', False), ('prato__isnull', True)), _connector='OR'), name='item_prato_ou_combo'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gte', 1)), name='quantidade_positiva'),
        ),
    ]
