# Generated by Django 5.2.17 on 2026-09-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cardapio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prato",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("entrada", "Entradas"),
                    ("principal", "Pratos principais"),
                    ("acompanhamento", "Acompanhamentos"),
                    ("sobremesa", "Sobremesas"),
                    ("bebida", "Bebidas"),
                    ("outros", "Outros"),
                ],
                default="outros",
                max_length=20,
            ),
        ),
    ]
